### ISSUE TITLE
How to use extension after installing from market place

### ISSUE THREAD

**Issue by trampster** [AvaloniaUI/Avalonia.VSCodeExtension#4]
I found the extension from the marketplace and installed it.

I checked a axaml file but got no code completion.

After installing the extension page in vscode under details there is a How to run section which tells you to run a node_modules command and press F5 in VSCode, but that command doesn't work.(bash: node_modules/.bin/rollup: No such file or directory)

And F5 just runs my avalonia application.

I think those instructions are for if you have the source code not if you have installed the extension from the market place.

I'm using vscode on linux (ubuntu)

**Comment by trampster** [comment]
I did notice that there is an Avalonia icon on the left dock, but clicking it just opens an empty panel.

The thing I'm really interested in is the axaml code completion.

**Comment by trampster** [comment]
Here is the Empty Avalonia left pane.
![image](https://user-images.githubusercontent.com/2063633/154606839-1739cce1-0504-4455-8379-99256568c568.png)

**Comment by trampster** [comment]
Here is my trying to get auto complete for the IsVisible property.

![image](https://user-images.githubusercontent.com/2063633/154607414-9d811930-46df-4034-be55-b3d084370f6d.png)

**Comment by aboimpinto** [comment]
Thanks for testing.
This is not "yet" the last version. We are testing the deployment process and the compatibility between all the operating systems (Windows, Linux, and Mac)

all these issues will be addressed separately ...

one again ... thanks

**Comment by SteMMo33** [comment]
I confirm the same problems on Debian 11.
Will be present a axaml preview for views or controls ?

**Comment by aboimpinto** [comment]
> Will be present a axaml preview for views or controls ?

Yes, the idea is to have some kind of preview of the Window, UserControls and Styles

**Comment by arloan** [comment]
Same here, macOS Monterey 12.2.1.

Still didn't figure out where is the `node_modules` folder.

**Comment by aboimpinto** [comment]
this extension is not been published anymore ... 

use: 

- https://github.com/AvaloniaUI/Avalonia.AxamlAutoCompletion 
For AutoCompletion 

- https://github.com/AvaloniaUI/Avalonia.TagsAndIdentation
For closing aXAML tags

**Comment by trampster** [comment]
@aboimpinto those extension are not available in the vscode Marketplace.
